spring.application.name=b2_pensionat_customer
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/pensionat_db
spring.datasource.username=dbUser512
spring.datasource.password=password
server.port= 8081